
# Site settings
title:       OpenStreetMap Ghana
logo:        /images/general/osmghana-logo-nav.png
description: OpenStreetMap (OSM) Ghana not-for-profit community making maps that saves lives and building capicity
baseurl:     '' # The subpath of your site, e.g. /blog
url:         http://osmghana.org # The base hostname & protocol for your site
twitter:     https://twitter.com/OSMGhana
facebook:    https://www.facebook.com/OSMGhana
twitter_username: OSMGhana
email : kasa@osmghana.org
# instagram:   

markdown:  kramdown
permalink: /:title
paginate:  9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Theme
theme_version: 1.0.3

# Tags
tag_page_dir:        tag
tag_page_layout:     tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  enockseth:
    name:     Enock Seth Nyamador
    bio:      Open Source evangelist. FOSSGIS Specialist and enthusiast
    gravatar: https://secure.gravatar.com/avatar/25c00329fd45ff820497f9c8c2d79dd3
    email:    enokc.seth@gmail.com
    website:  http://enockseth.gitlab.com
    # github:   
    twitter:  https://twitter.com/enock4seth

  stevdok:
    name:     Mawutor Donkor
    bio:      I capture street level images
    # gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:    stevdok@gmail.com
    website:  http://stevdok.com
    # github:   
    twitter:  https://twitter.com/stevdok

  abigail:
    name:    Abigail Darko 
    bio:     Business Administrations and Technology
    # gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    # email:    
    # website: 
    # github:   
    # twitter:  

  fidel:
    name:    Fidel Nyameke 
    bio:     Network engineer
    # gravatar: https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    # email:    
    # website: 
    # github:   
    # twitter: 

  sammyhawkrad:
    name:     Samuel Darkwah Manu
    bio:      GIS Enthusiast
    gravatar: https://secure.gravatar.com/avatar/66f6e61a0ac1316dd912f349df9bb96c
    email:    manusam14@yahoo.com
    website:  http://sammyhawkrad.github.io
    github:   https://github.com/sammyhawkrad
    twitter:  https://twitter.com/sammyhawkrad 